import"./assets/styles-DngmrvAk.js";import{i as d}from"./assets/vendor-I1I71QQ2.js";const f="https://dummyjson.com",n=12;async function b(){const t=await fetch(`${f}/products/categories`);if(!t.ok)throw new Error("Failed to fetch categories");return t.json()}async function _(t=1){const o=(t-1)*12,s=await fetch(`${f}/products?limit=12&skip=${o}`);if(!s.ok)throw new Error("Failed to fetch products");return s.json()}async function $(t,o=1){const s=(o-1)*n,r=await fetch(`${f}/products/category/${t}?limit=${n}&skip=${s}`);if(!r.ok)throw new Error("Failed to fetch category");return r.json()}async function k(t){const o=await fetch(`${f}/products/${t}`);if(!o.ok)throw new Error("Failed to fetch product");return o.json()}async function B(t){const o=await fetch(`${f}/products/search?q=${t}`);if(!o.ok)throw new Error("Failed to fetch search results");return o.json()}function v(t,o){const s=t.map(r=>`<li class="categories__item">
        <button class="categories__btn" type="button">${r.name}</button>
      </li>`).join("");o.innerHTML=s}function h(t,o){const s=t.map(({id:r,title:c,thumbnail:u,brand:p,category:m,price:y})=>`
    <li class="products__item" data-id="${r}">
      <img class="products__image" src="${u}" alt="${c}" />
      <p class="products__title">${c}</p>
      <p class="products__brand"><span class="products__brand--bold">Brand:</span> ${p}</p>
      <p class="products__category">Category: ${m}</p>
      <p class="products__price">Price: $${y}</p>
    </li>`).join("");o.innerHTML=s}function w(t){t.classList.add("not-found--visible")}function g(t){t.classList.remove("not-found--visible")}function F(t){t.classList.add("modal--is-open")}function C(t){t.classList.remove("modal--is-open")}function M(t,o){const{title:s,description:r,price:c,thumbnail:u,tags:p=[]}=t,m=p.map(y=>`<li>#${y}</li>`).join("");o.innerHTML=`
    <img class="modal-product__img" src="${u}" alt="${s}" />
    <div class="modal-product__content">
      <p class="modal-product__title">${s}</p>
      <ul class="modal-product__tags">${m}</ul>
      <p class="modal-product__description">${r}</p>
      <p class="modal-product__shipping-information">Shipping: Free worldwide</p>
      <p class="modal-product__return-policy">Return Policy: 30 days</p>
      <p class="modal-product__price">Price: $${c}</p>
      <button class="modal-product__buy-btn" type="button">Buy</button>
    </div>`}const e={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),notFoundBlock:document.querySelector(".not-found"),loadMoreBtn:document.querySelector(".load-more-btn"),searchForm:document.querySelector(".search-form"),searchInput:document.querySelector(".search-form__input"),searchClearBtn:document.querySelector(".search-form__btn-clear"),modal:document.querySelector(".modal"),modalContent:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),wishlistCounter:document.querySelector("[data-wishlist-count]"),cartCounter:document.querySelector("[data-cart-count]")};let a=1,l="All",L=!1;S();async function S(){try{const t=await b();t.unshift({name:"All"}),v(t,e.categoriesList),a=1,l="All";const o=await _(a);h(o.products,e.productsList),g(e.notFoundBlock),i(o.total>n)}catch{d.error({message:"Failed to initialize page",position:"topRight"})}}e.categoriesList.addEventListener("click",q);async function q(t){if(t.target.nodeName!=="BUTTON")return;const o=t.target.textContent;l=o,a=1;const s=e.categoriesList.querySelectorAll(".categories__btn");s.forEach(c=>c.classList.remove("categories__btn--active"));const r=Array.from(s).find(c=>c.textContent.trim()===l);r&&r.classList.add("categories__btn--active");try{let c;o==="All"?c=await _(a):c=await $(o,a),c.products.length?(h(c.products,e.productsList),g(e.notFoundBlock),i(c.total>n)):(e.productsList.innerHTML="",w(e.notFoundBlock),i(!1))}catch{d.error({message:"Failed to load category",position:"topRight"})}}e.loadMoreBtn.addEventListener("click",A);async function A(){if(!L){L=!0,e.loadMoreBtn.disabled=!0,a+=1;try{let t;if(l==="All"?t=await _(a):t=await $(l,a),!t.products.length||a*n>=t.total){i(!1),d.info({message:"All products loaded",position:"topRight"});return}const o=t.products.map(({id:s,title:r,thumbnail:c,brand:u,category:p,price:m})=>`
      <li class="products__item" data-id="${s}">
        <img class="products__image" src="${c}" alt="${r}" />
        <p class="products__title">${r}</p>
        <p class="products__brand"><span class="products__brand--bold">Brand:</span> ${u}</p>
        <p class="products__category">Category: ${p}</p>
        <p class="products__price">Price: $${m}</p>
      </li>`).join("");e.productsList.insertAdjacentHTML("beforeend",o),a*n>=t.total&&(i(!1),d.success({message:"All products loaded",position:"topRight"}))}catch{d.error({message:"Failed to load more products",position:"topRight"})}finally{L=!1,e.loadMoreBtn.disabled=!1}}}e.productsList.addEventListener("click",E);async function E(t){const o=t.target.closest("li.products__item");if(!o)return;const s=o.dataset.id;try{const r=await k(s);M(r,e.modalContent),F(e.modal)}catch{d.error({message:"Failed to load product info",position:"topRight"})}}e.modalCloseBtn.addEventListener("click",()=>C(e.modal));e.searchForm.addEventListener("submit",P);async function P(t){t.preventDefault();const o=e.searchInput.value.trim();if(o){l="Search",a=1;try{const s=await B(o);s.products.length?(h(s.products,e.productsList),g(e.notFoundBlock),i(s.total>n)):(e.productsList.innerHTML="",w(e.notFoundBlock),i(!1))}catch{d.error({message:"Failed to perform search",position:"topRight"})}}}e.searchClearBtn.addEventListener("click",async()=>{e.searchInput.value="",a=1,l="All";const t=await _(a);h(t.products,e.productsList),g(e.notFoundBlock),i(t.total>n)});function i(t){t?e.loadMoreBtn.classList.remove("visually-hidden"):e.loadMoreBtn.classList.add("visually-hidden")}
//# sourceMappingURL=index.js.map
